version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: pip install awscli --upgrade --user
      - run: aws s3 sync build s3://app.keendly.com/ --delete